# Generated by Django 2.2.7 on 2019-12-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coding_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linecode', models.CharField(db_column='linecode', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
            ],
            options={
                'db_table': 'coding_line',
            },
        ),
        migrations.CreateModel(
            name='coding_terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
            ],
            options={
                'db_table': 'coding_terminal',
            },
        ),
        migrations.CreateModel(
            name='distance_route_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startcode', models.CharField(db_column='startcode', max_length=50)),
                ('startname', models.CharField(db_column='startname', max_length=50)),
                ('endcode', models.CharField(db_column='endcode', max_length=50)),
                ('endname', models.CharField(db_column='endname', max_length=50)),
                ('distance', models.DecimalField(db_column='distance', decimal_places=4, max_digits=8)),
                ('route', models.TextField(db_column='route')),
                ('sitenum', models.CharField(db_column='sitenum', max_length=50)),
                ('price', models.CharField(db_column='price', max_length=50)),
            ],
            options={
                'db_table': 'distance_route_price',
            },
        ),
        migrations.CreateModel(
            name='transfer_terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
            ],
            options={
                'db_table': 'transfer_terminal',
            },
        ),
        migrations.CreateModel(
            name='line8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line8',
            },
        ),
        migrations.CreateModel(
            name='line7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line7',
            },
        ),
        migrations.CreateModel(
            name='line6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line6',
            },
        ),
        migrations.CreateModel(
            name='line4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line4',
            },
        ),
        migrations.CreateModel(
            name='line3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line3',
            },
        ),
        migrations.CreateModel(
            name='line2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line2',
            },
        ),
        migrations.CreateModel(
            name='line12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line12',
            },
        ),
        migrations.CreateModel(
            name='line11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line11',
            },
        ),
        migrations.CreateModel(
            name='line1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalcode', models.CharField(db_column='terminalcode', max_length=50)),
                ('terminalname', models.CharField(db_column='terminalname', max_length=50)),
                ('linename', models.CharField(db_column='linename', max_length=50)),
                ('firsttime', models.DateTimeField(db_column='firsttime')),
                ('lasttime', models.DateTimeField(db_column='lasttime')),
                ('wfirsttime', models.DateTimeField(db_column='wfirsttime')),
                ('wlasttime', models.DateTimeField(db_column='wlasttime')),
                ('adjacentdistance', models.DecimalField(db_column='adjacentdistance', decimal_places=4, max_digits=8)),
                ('linecode', models.ForeignKey(db_column='linecode', on_delete=django.db.models.deletion.CASCADE, to='subways.coding_line')),
            ],
            options={
                'db_table': 'line1',
            },
        ),
    ]
